var words = ["Arbys cares. Apr 01, 2017 ", 
"Arbys wants to remind you to save money avoiding high insurance premiums since no one cares if you live or die. ArbyCare® Enjoy arbys Mar 24, 2017 ", 
"This St Patrick's day don't forget that...wait, what? It was yesterday? Eh, whatever. Eat arbys. Mar 18, 2017 ", 
"Tonight at arbys: no one cares. Kill. Die. OD. Sleep over. Whatever. We can't express this enough: we don't care. Eat arbys Mar 15, 2017 ", 
"In honor of #InternationalWomensDay we're grinding up living beings in a giant machine, because fuck it. That's just how we do. Enjoy arbys Mar 08, 2017 ", 
"The best part of this new healthcare plan is that here at arbys, we were all ready to die anyway. Eat arbys Mar 08, 2017 ", 
"Look in the corner you sleep in Now look in the corner you defecate in Now look in the corner you cry for your dead dreams in Eat arbys lol Mar 02, 2017 ", 
"This Ash Wednesday head down to arbys where everyone here has had black shit smeared all over our faces for weeks now Enjoy arbys Mar 01, 2017 ", 
"Eat McDonald's. Oh...wait. I read that wrong. Eat arbys. Feb 27, 2017 ", 
"Bc they get such little attention, tonight we're giving celebs solid gold dick shaped man statues so they can fuck themselves more Eat arbys Feb 27, 2017 ", 
"every single person you've ever loved will either go to your funeral or you will go to theirs. Afterwards, why not go to arbys? Feb 24, 2017 ", 
"Hey gang! This Presidents' Day remember: regardless of your political affiliation, you're closer to death than you've ever been Eat arbys. Feb 20, 2017 ", 
"Roses are red Violets are blue Nobody gives A shit about you Come down to arbys Shoot some black tar Cry for yr dead dreams die in your car Feb 14, 2017 ", 
"Here's the thing about beyonce's performance: the Grammys are stupid and we're hurling incontrovertibly towards eternal doom. Eat arbys. Feb 13, 2017 ", 
"So Beyoncé is pregnant w twins, eh? Who cares? We're all gonna die. Enjoy arbys Feb 01, 2017 ", 
"No matter what country you're from, Arbys is happy to remind you that you're all banned from entering heaven bc it doesn't exist. Eat Arbys Jan 29, 2017 ", 
"During these uncertain times, Arbys stands w those of you just trying to get high in this bathroom stall & maybe fuck a little. Enjoy Arbys Jan 26, 2017 ", 
"Today is a perfect day to march down to Arbys and abort your hunger. Enjoy Arbys. Jan 21, 2017 ", 
"Tonight as half the nation cries and the other half enthusiastically fucks members of their immediate family, remember: Arbys exists for now Jan 21, 2017 ", 
"Daddy, where were you when the world ended? Hooo, boy, I remember it like it was just now. I was at Arbys sucking off a hobo. Enjoy Arbys Jan 20, 2017 ", 
"Only 3 more days until Americans can legally fuck their daughters. Not that it matters. Law is the dead twin to a dead God Enjoy Arbys Jan 18, 2017 ", 
"This MLK day, sic the dogs on your hunger w a Beef n cheddar & hose down your thirst with a delicious fountain drink from Arbys Enjoy Arbys Jan 16, 2017 ", 
"There's no god It's Friday. Enjoy Arbys Jan 13, 2017 ", 
"Arbys: piss on whoever you want. Jan 11, 2017 ", 
"What do Trump, Meryl Streep, & pregnant chewbacca mom have in common? Soon enough, they'll all be dead Eat Arbys Jan 09, 2017 ", 
"Mommy, why are ppl at this Arbys all dressed up? They were at church God cares how they dress? Oh baby, there's no god. Only pain & death Jan 08, 2017 ", 
"Welp, it's the new year. Either you died last night or you didn't. Not sure which is worse. Here's to postponing the inevitable. Eat Arbys Jan 01, 2017 ", 
"And time lurches relentlessly forward in a death march, culminating in brutal suffering, the end of all things & eternal blackness Eat Arbys Dec 31, 2016 ", 
"What's your favorite dipping shit to dunk our #crap in, or whatever? Fuck this. Eat Arbys Dec 28, 2016 ", 
"It's been a rough weekend. Wash the taste of your uncle's dick out of your mouth w some Arbys tonight and start anew tomorrow Enjoy Arbys Dec 27, 2016 ", 
"You're just waking up. It's 3pm. Your mouth reeks of semen & gin. The speed is gone. So is your family. It's Xmas at Arbys No gods No Santas Dec 25, 2016 ", 
"Hey kids! It's Xmas eve. Anyway, Santa's not real and soon your parents will be dead. Enjoy Arbys Dec 24, 2016 ", 
"Only 2 days left to lie to all the stupid children in your family who still believe in Jesus. Have a holiday, from Arbys Dec 23, 2016 ", 
"This guy was one of the elite few to go to space and also live to be 95, and still, today he's nothing. You're somehow even less. Eat Arbys Dec 08, 2016 ", 
"Q: How is our new Fire Roasted Philly sandwich like the city of Philadelphia? A: Both are comprised mostly of assholes Enjoy Arbys Nov 29, 2016 ", 
"We, too, have discontinued the Cuban. Enjoy Arbys Nov 26, 2016 ", 
"In honor of all you fatty animals ripping each other to shreds in Walmart for a slightly cheaper TV, Arbys is serving shredded animals today Nov 25, 2016 ", 
"Thanks for nothing. Enjoy Arbys Nov 25, 2016 ", 
"This turkey day, kill your neighbors & just live in their house. Have your kids build a pipeline over their corpses enjoy football Eat Arbys Nov 24, 2016 ", 
"This Veterans Day, why not suffer from ptsd in an underfunded hospital contemplating your lack of legs while the govt ignores you? Eat Arbys Nov 11, 2016 ", 
"To the half the nation that suddenly feels doomed: you've always been doomed The other half celebrates like they ain't doomed too. Heh Arbys Nov 09, 2016 ", 
"Whatever. Cut up more animals. Eat Arbys #Elections2016 Nov 09, 2016 ", 
"Tomorrow, don't for get to vote for the pile of meat covered in slime that best represents your shitty, one sided world view. Eat Arbys Nov 07, 2016 ", 
"Last night, several lifelong Cubs fans died during the game, missing the culmination of their pointless existences by mere seconds Eat Arbys Nov 03, 2016 ", 
"This Halloween remember: no matter how many children you lure into your windowless van, you'll ultimately die alone. Enjoy Arbys. Oct 31, 2016 ", 
"Vine is a lot like life: short, pointless and swarming with idiots. Enjoy Arbys Oct 27, 2016 ", 
"The Cubs are like those erection pills in your wallet, in that no matter how well they perform tonight, she doesn't love you anymore Arbys Oct 27, 2016 ", 
"World Series prediction: all players on both teams will die & their World Series rings will offer no comfort as they face doom Eat Arbys Oct 26, 2016 ", 
"What do we want? To die! When do we want it? Who gives a shit! Eat Arbys. Oct 11, 2016 ", 
"Look at the bright side: soon the sun will swallow the earth, erasing humanity from the universe forever Eat Arbys Oct 08, 2016 ", 
"You know what will grab you by the pussy and do whatever it wants: the cold, unfeeling dead hand of encroaching doom. Enjoy Arbys Oct 08, 2016 ", 
"Arbys: come for the sandwiches. Stay because you died shooting heroin into your dick in the ladies room. Enjoy Arbys Oct 07, 2016 ", 
"Today for lunch why not brutally bind your hunger with duct tape & throw it in the tub with a big scary meal from Arbys? Arbys: Bon appetit Oct 04, 2016 ", 
"Nothing says \"who gives a shit\" like shameless merchandising so fuck it. Get your shirts now, as death comes quickly https://t.co/M3XOookpHY Oct 04, 2016 ", 
"Happy Monday It's a good day to suck penises behind Arbys for one of our affordable, limited time smoke mountain sandwiches Enjoy your Arbys Oct 03, 2016 ", 
"You'll die alone. There is no debate. Eat Arbys. Sep 27, 2016 ", 
"We've all done things we aren't proud of. Dark things. Things we'd never even tell our spouses. Things piled up in the shed. Eat Arbys. Sep 25, 2016 ", 
"Happiness is a lie Arbys Pestilence Plague You stink Faith is for fools Rum I need pills Death can't come soon enough Arbys You are doomed Sep 23, 2016 ", 
"You called it: Brad & Angelina are divorcing. Meanwhile, you'll never divorce because no one will ever love you even for a moment. Eat Arbys Sep 20, 2016 ", 
"9-12-01 Never forget Enjoy arbys Sep 13, 2016 ", 
"Today, fly your hunger into Arbys for meal deals so hot they could melt steel beams. Enjoy Arbys. Sep 11, 2016 ", 
"Hey @apple, Here at Arbys 7.0, our \"jack off\" policy is, \"eh, who cares? Go for it,\" and there's very little outrage. Arbys:Go fuck yourself Sep 07, 2016 ", 
"Awaken Arise Defecate Labor Consume the flesh, alcohol & pills Ignore the pain Feel your dreams die Slumber Repeat Await death Enjoy Arbys Sep 05, 2016 ", 
"In honor of Labor Day we're making all our employees come into work because fuck them. Enjoy Arbys Sep 04, 2016 ", 
"Hey gang! TGIF! This weekend, statistically, a few of you will die. Eat Arbys Sep 02, 2016 ", 
"Arbys sits for the pledge because Arbys is WAAAY too high to pretend to care about the twin dead fictions of God & America Enjoy Arbys Aug 30, 2016 ", 
"Hey gang, as you head out to party, remember this handy rhyme: Friday night-sexy delight Saturday morning-get to aborting Enjoy Arbys Aug 26, 2016 ", 
"The Olympics have ended, and soon all these beautiful, world class athletes will go back to pumping gas. Every dream dies. Eat Arbys Aug 22, 2016 ", 
"Don't you hate washing your hands? Ever just skip it? Us too. What's the fucking point? Enjoy Arbys Aug 20, 2016 ", 
"Usain bolt running is a lot like life: over remarkably fast, and like 2 days after that, no one on earth gives a shit. Enjoy Arbys Aug 19, 2016 ", 
"Hey @RyanLochte, why not swim on down to Arbys and piss all over our walls too? Everyone else here is. Enjoy Arbys Aug 18, 2016 ", 
"RT if every waking moment is an agonizing misery and the sweet embrace of death can't come quickly enough. Enjoy Arbys Aug 16, 2016 ", 
"On this Sunday let's thank the heavens for Arbys: a place for revolting dipshits like you to creep towards death in a cruel godless universe Aug 14, 2016 ", 
"Remember: there's always someone younger faster & smarter than you so you may as well do a few more lines of coke & keep crying Enjoy Arbys Aug 11, 2016 ", 
"Hey second amendment people, today, why not assassinate your hunger at Arbys, the Supreme Court of deliciousness. Aug 09, 2016 ", 
"#firstsevenjobs Arbys Sucking dicks: crack Arbys Sucking dicks: heroin Arbys Sucking dicks: glue Arbys Social media director Enjoy Arbys Aug 06, 2016 ", 
"Tonight as the nations of earth converge atop a smoldering mass of fecal matter & despair, remember: the Olympics are fucking dumb Eat Arbys Aug 05, 2016 ", 
"Q: How's Orlando bloom's dick like a beef n cheddar? A: both are just distractions from the pain of life & inevitability of death Eat Arbys Aug 04, 2016 ", 
"Fuck babies. They're stupid and weak. Enjoy Arbys Aug 02, 2016 ", 
"For those of you who care about things, we offer several sandwiches that strongly resemble Bernie sanders. Enjoy Arbys. Jul 27, 2016 ", 
"Dems and republicans have their differences but one thing brings us all together: everyone dies alone & is quickly forgotten Eat Arbys Jul 26, 2016 ", 
"(Borat voice) MY LIIIIFE... ...is a meaningless misery sandwiched between 2 infinite voids Enjoy Arbys Jul 21, 2016 ", 
"\"Mommy, why is God letting me die?\" \"Oh sweetie, don't be silly. There's no God. Now here, eat your Arbys while you still can.\" Arbys Jul 20, 2016 ", 
"Arbys was extremely inspired by melania's RNC speech last night. Arbys: eat fresh Jul 19, 2016 ", 
"Sup #teens? Yo, peep this: All those Pokemon will die and rot in the eternal blackness of the virtual void. Enjoy Arbys 💯 Jul 11, 2016 ", 
"As the world crumbles to black ash why not wash down those pills w gin & head down to Arbys to piss away your last few moments of existence? Jul 10, 2016 ", 
"Sad? Hungover? Trapped in a shitty sham marriage? Look at the bright side: soon you'll be dead & everyone will forget you even existed Arbys Jul 05, 2016 ", 
"Happy birthday, America, you shitty dead dream, you. Enjoy Arbys Jul 04, 2016 ", 
"If you eat at arbys, every single member of ISIS will someday die. So will you and everyone you've ever loved. Enjoy Arbys. Jun 29, 2016 ", 
"Fuck it. We're now offering abortions as our #12 meal deal. Get em while they're hot, or whatever. Enjoy Arbys. You're eating for one now. Jun 27, 2016 ", 
"Here at Arbys we are so fucking gay. All of us. So gay. Just so, so, so gay. Happy pride. Jun 26, 2016 ", 
"What the fuck is Europe and who gives a shit? Enjoy Arbys. Jun 24, 2016 ", 
"How is Arbys like the senate? There are a bunch of useless old people scattered around on our floor just waiting to die too. Eat Arbys. Jun 23, 2016 ", 
"Hey Arbys fans. It's hump day. you know what that means: we're all fucked and tomorrow we'll be full of regret. Today, be full of Arbys Jun 22, 2016 ", 
"Enjoy Arbys. The official meat or sandwiches or something of whatever bullshit you're stupid enough to believe in today Jun 21, 2016 ", 
"This Father's Day, run out for a quick beef n cheddar and never come back. Enjoy Arbys. Jun 19, 2016 ", 
"Life hack: just go ahead and die. Then you won't have to untangle any more fucking cords ever again. Enjoy Arbys Jun 16, 2016 ", 
"That awkward feeling when you're a useless speck of decaying matter sitting at arbys high on glue, just crying amongst the hobos Eat Arbys Jun 16, 2016 ", 
"People asking \"why would a kind god kill innocent babies?\" Miss the point There's no god Babies are weak as shit Everything dies Enjoy Arbys Jun 09, 2016 ", 
"Seatbelts are for pussies. God is for cowards. Death is forever. Drugs are for numbing yourself to the horror of eternity Arbys is for lunch Jun 06, 2016 ", 
"Statistically, no one loves you. No one has even ever heard of you. Enjoy Arbys, you completely irrelevant turd Jun 03, 2016 ", 
"So they kicked you out of @McDonalds? Well, who cares? Time to head down to Arbys where everyone is as fucking disgusting as you Eat Arbys Jun 01, 2016 ", 
"If you think today sucks, consider this: soon you'll be older, closer to death & longing to relive this horrible, shitty day. Enjoy Arbys May 31, 2016 ", 
"Aren't you dying (on the beach at Normandy, in the ratholes in Nam, in the deserts of Iraq & Afghanistan) for some Arbys? Happy Memorial Day May 30, 2016 ", 
"Welcome to Arbys You already experienced the eternal nothingness of death before you were born & soon you'll die again How may I help you? May 26, 2016 ", 
"It rubs the Arbys on its skin or else it gets the hose again May 19, 2016 ", 
"Used needles, empty bottles & that new bourbon sandwich thing we do are everywhere. She looks dead. I'm thinkin lets bail. I'm thinkin Arbys May 18, 2016 ", 
"Monday morning The coke is almost gone The gin is hot The car smells like blood Time for one last stop at Arbys before you get to the bridge May 16, 2016 ", 
"Church is like life in that the best part is when it ends and you go back to being positive there's no god Happy Sunday from Arbys May 15, 2016 ", 
"Now that you're done with your Saturday morning abortion why not head on down to Arbys & put more questionable meat in you? Enjoy Arbys May 14, 2016 ", 
"They say today's bad luck, &, like all other days, it is. But look at it this way: at least it's Friday & soon we'll all be dead. Eat Arbys May 13, 2016 ", 
"So @tacobell kinda gets life: No matter how you put this bullshit together, & no matter what you call it, it's the same garbage Enjoy Arbys May 12, 2016 ", 
"Your mother is so fucking ashamed of you. But Arbys couldn't give less of a shit. Enjoy Arbys. May 08, 2016 ", 
"Hey @SUBWAY go fuck yourself. sincerely, Arbys May 07, 2016 ", 
"Here at Arbys we've got the greatest, best taco bowls What's that? We don't? Huh. Eh, who gives a shit? Arbys: the best taco bowls May 05, 2016 ", 
"¡Happy cinco de mayo from Arbys! No Juan could give less of a shit about your stupid, pointless existence. Eat Arbys. Olé. May 05, 2016 ", 
"Enjoy saying 'may the fourth be with you' to each other, you pathetic virgins. Eat Arbys May 04, 2016 ", 
"Election prediction: some shithead will seize power & shepherd us into the sweet eternal void of godless death. Nothing matters. Enjoy Arbys May 03, 2016 ", 
"They burned his village Slew his parents he eats dirt to quell unbearable hunger pains You're full, but fuck it Finish those fries Eat Arbys Apr 27, 2016 ", 
"The night is dark and full of terrors, then you die. Enjoy Arbys. Apr 24, 2016 ", 
"Happy 420 from Arbys. Nothing says \"fuck it\" quite like celebrating getting high on hitler's birthday. \"At least they have an ethos\" my ass. Apr 20, 2016 ", 
"nothing matters. There is no anything. Sentience itself is an illusory fever dream https://t.co/laQVjRIZvd Apr 14, 2016 ", 
"Yo. It's lunchtime selfie time here at Arbys, y'all. https://t.co/pos3Flgg9H Apr 13, 2016 ", 
"Every 8 ball is a magic 8 ball if you have keys and you're in the stall in an Arbys restroom. Enjoy Arbys. Your appetite is probably gone. Apr 12, 2016 ", 
"Awaken Arise Chug gin Defecate yesterday's Arbys Toil Eat Arbys More gin Masturbate in the dark in solitude Sleep Repeat Die Be forgotten Apr 09, 2016 ", 
"I don't know what you have planned for your Friday, but im'a gather up the chaps and head to arbys to work the glory holes in the men's room Mar 18, 2016 ", 
"My arbys lies over the ocean My arbys lies over the sea Nobody cares that you're Irish, wee lass You smell like vomit & pee Enjoy arbys Mar 17, 2016 ", 
"Sandwich is delicious. What's the fucking problem, john? Eat arbys and get fucked. There's no god https://t.co/VCJmY0C2TR Mar 12, 2016 ", 
"That awkward moment when you realize we're all just a bunch of short fingered vulgarians, irrationally greasy, full of arbys, waiting to die Mar 10, 2016 ", 
"Dear leader Kim Jong looks like he's had Un too many of our loaded Italians. Srsly tho, he's gonna blow up the world, so fuck it. Eat Arbys Mar 04, 2016 ", 
"Today's special: find the guy at each arbys who'll buy you lunch if you go in the alley, close your eyes & suck horsey sauce out of a hose Mar 02, 2016 ", 
"Trump: a sentient beef n cheddar who cares for nothing save his own immediate pleasure as he courts the end of all things choose doom Arbys Mar 01, 2016 ", 
"If only the construct we cling to in order to rationalize our impending doom had a clerical anomaly today that we could exploit to sell food Feb 29, 2016 ", 
"This concludes a shitty bit of your existence wasted seeing what a sandwich thinks about idiot millionaires jacking each other off Eat arbys Feb 29, 2016 ", 
"Welcome to arbys We're all doomed to be part of an in memoriam montage that no one will watch, care about or know existed For here or to go? Feb 29, 2016 ", 
"Ryan seacrest: a talentless cipher sent to guide you through the vapid happenings of a braindead cultural elite There was never a god Arbys Feb 29, 2016 ", 
"Sometimes the bear eats you, bro. Hey Leo: life is a meaningless exercise in futility. Good luck Eat arbys Fuck models Die alone, regardless Feb 28, 2016 ", 
"The carpet, red with the blood of thousands of cows, slain and drained so you may stave off eternal blackness one more day #oscars eat arbys Feb 28, 2016 ", 
"In honor of leap year we'll offer a vegetarian menu as though it matters at all. Have fun social media 'journalists.' Everything dies. Arbys Feb 26, 2016 ", 
"If you want to worship an orange pile of garbage with a reckless disregard for everything, get on down to arbys & try our loaded curly fries Feb 24, 2016 ", 
"As they shutter Guantanamo, turns out it does nothing to allay the torture that is sentience. Damn, Daniel, let's go to arbys. Feb 23, 2016 ", 
"Jeb Bush sits alone at arbys The flesh tastes of dust to him The void beckons The lights go off The slaves go home And yet Jeb sits Alone Feb 21, 2016 ", 
"Another day, another meaningless tribute to a dead God. https://t.co/sYxCVDbuRt Feb 19, 2016 ", 
"\"Things are never as bad as they seem. Also, I'm dead.\" -Harper Lee Eat arbys Feb 19, 2016 ", 
"Think of it this way: if there were an afterlife, all your grandmas would know the creepy shit you beat off to Arbys: no gods no witnesses Feb 16, 2016 ", 
"Roses are red violets are blue Love's an illusion Sentience too Nobody cares No one loves you back Please enjoy arbys Fade into black Feb 14, 2016 ", 
"Antonin Scalia: welcome to the realization that once it goes black, you never come back. Eat at arbys Feb 13, 2016 ", 
"Kanye is like this guy furiously jacking off in his booth here at arbys: everyone sees what you're doing, but no one cares, dude Enjoy arbys Feb 13, 2016 ", 
"Got some time on your hands? Why not get on down to arbys? Wait, no...not time, blood & semen. Get in here. We don't give a shit Enjoy arbys Feb 11, 2016 ", 
"This Ash Wednesday, why go to mass when you can just swing by any arbys & let some pervert smear filth on your face in a bathroom stall? E Feb 10, 2016 ", 
"If you can't shit your pants after eating chipotle anymore, why not come suck off a stranger at arbys? Arbys: No judgment No cameras No gods Feb 08, 2016 ", 
"Listen to Coldplay. Feb 08, 2016 ", 
"If the Rams win, we die alone. If the raiders win sentience is a fever dream. If either team actually playing wins nothing matters Eat arbys Feb 07, 2016 ", 
"ARB-Ye ready for the Big Game? Arb ye ready for blackout wastedness, sex w strangers, a brutal shame spiral & a dignity-free death?Eat arbys Feb 07, 2016 ", 
"Here at arbys we're gearing up for tomorrow's Big Game: the game where we ignore our impending doom & rationalize our ugly meaningless lives Feb 06, 2016 ", 
"That groundpig thing saw its shadow, eh? According to the lore that means no one gives a shit about you & all life ends in pain Eat arbys Feb 02, 2016 ", 
"As they line up to rule us we, the damned, line up to die. What happens in the void? Not a ton of arbys. Eat Arbys now It's already too late Feb 02, 2016 ", 
"By morning she'll be dead anyway & she can't take those Oxys with her. Suffocate your grandmother real quick, get turnt & get down to arbys. Jan 29, 2016 ", 
"On the 30th anniversary of the challenger exploding, shuttle on down to arbys for lunch then wind up dead & alone in blackness. Eat arbys Jan 28, 2016 ", 
"Yo #kanye! Arbys has beef too! The beef of millions of cow carcasses that will, like you, be forgotten in a godless unfeeling void Eat arbys Jan 27, 2016 ", 
"When the fire rains down from the skies, boiling the rivers of blood as soldiers massacre the weak, Arbys'll still be here, fucking yer moms Jan 27, 2016 ", 
"Yo #teens! While you're out there gettin rad remember that your death is 💯% inevitable & all life is meaningless, bae. So fuck it Eat arbys. Jan 20, 2016 ", 
"I have a dream: a dream of 6.5 billion rotting piles of meat slouching off toward the inevitable permanence of death. Enjoy arbys Jan 18, 2016 ", 
"If you've never peddled the flesh of subhuman garbage creatures to human garbage, you've never lived, and living is a nightmare. Eat arbys Jan 14, 2016 ", 
"Powerball is a great metaphor for life in that it's a huge waste of time and only idiot losers think they stand a chance. Enjoy arbys Jan 13, 2016 ", 
"It's a good day to get some arbys. It's a good day to just keep on walking, to finish the gin & pills & die alone on the side of the highway Jan 05, 2016 ", 
"New Years resolution: give up. Eat arbys. Sit there. Keep sitting. Let the meaninglessness of life envelop you. Die. Be forgotten Jan 01, 2016 ", 
"Anything happen? Didn't think so. You're still fat and addicted to speed, dying. Happy new year from Arbys. Jan 01, 2016 ", 
"Tomorrow, another useless demarcation of the construct of time sets in. Get high and pretend you're not dying, there's no god. from arbys. Jan 01, 2016 ", 
"...only to die alone, bitter, without love, addicted, sucking penises out behind Arbys like the rest of us https://t.co/2BwWOPf27I Dec 26, 2015 ", 
"And another drone submits. Here at the end of 2015 come to grips with what to expect from the new year. Enjoy arbys https://t.co/jf3zns9FLC Dec 26, 2015 ", 
"\"There's no santa, billy. Hell, there's not even a god. It's just us, this basement full of greasy dildos, Arbys & the finality of death\" Dec 25, 2015 ", 
"It's almost time to drunkenly cram your shitty kids' stockings full of Arbys sandwiches & pass out in the snow Merry Christmas, from arbys Dec 24, 2015 ", 
"Something something Star Wars something something arbys. Star Wars, arbys. Arbys, Star Wars. Whatever. You get it. Who fucking cares? Dec 17, 2015 ", 
"This holiday season, wash down that beef & cheddar w a few handfuls of grandma's pills. She won't need em where she's going. Enjoy arbys Dec 16, 2015 ", 
"credible terror threat: sentience & the soul are illusions.Everyone you love will die scared & alone Your life will be forgotten Enjoy arbys Dec 15, 2015 ", 
"There's nothing like that first after-work bump of cocaine after a long, rough Monday of crying & beating off in your car. Enjoy arbys Dec 14, 2015 ", 
"In honor of john lennon's return to the void, beat your wife...in a friendly race down to arbys. Arbys: bigger than Jesus, realer than God. Dec 08, 2015 ", 
"On this, a date that lives in infamy, surprise your unsuspecting hunger with a tactical, 2 wave Arbys attack. Dec 07, 2015 ", 
"Arbys arbys arbys We made it out of cows And when they die get ready To cram them in your bowels Have a Hanukkah. Enjoy arbys. Dec 06, 2015 ", 
"Another slave to the void offers a pointless tribute. Enjoy arbys. https://t.co/yExXgfC2Nv Dec 03, 2015 ", 
"All Wendys customers will die scared, unfulfilled & alone, pleading w a nonexistent God for a few more shitty moments in this hell Eat Arbys Dec 02, 2015 ", 
"It's officially winter, when the lucky trees, plants and homeless all get to die. Thanks for enjoying arbys Dec 01, 2015 ", 
"It's Black Friday. You've laughed at stampeding fat people. You've choked a bitch for an Xbox. Now, hit up Arbys and get ready to die. Arbys Nov 28, 2015 ", 
"Hey gang! How was your thanksgiving? Nov 27, 2015 ", 
"Hi. I'm John madden. Soon I'll be dead. You will too. Here's a monstrosity of decadent gluttony that defies nature. Tursuckit, God Eat arbys Nov 27, 2015 ", 
"You sit alone in arbys, face shiny with grease and tears. Your family is thankful you're no longer around. Happy thanksgiving from Arbys Nov 26, 2015 ", 
"Recent events got you worried the world's going to hell? Arbys is here to remind you that this is already hell & there's no heaven Eat arbys Nov 25, 2015 ", 
"This Tuesday, arbys is thankful for the sweet inevitability of death & the pointlessness of life that makes morality irrelevant. Enjoy arbys Nov 24, 2015 ", 
"If you can't handle Arbys at our \"fuck this completely\" then you don't deserve us at our \"sentient happiness is an illusion.\" Enjoy Arbys. Nov 21, 2015 ", 
"Yo Arbys lovers! It's FRIDAY! Know what that means? It means you're 1 more pointless day closer to the eternal black void of death Eat arbys Nov 20, 2015 ", 
"Like pigs & cows Lined up to die So too you wait & softly cry Choke it down Stuff it in Wash your arbys Down w gin Throw up in the car Again Nov 19, 2015 ", 
"Ten years ago we had steve jobs, bob Hope and Johnny cash. Now they're all dead. It'll happen to you too. Enjoy arbys. Nov 17, 2015 ", 
"He died doing what he loved. Struggling against a very aggressive and untreatable cancer. Please enjoy arbys Nov 15, 2015 ", 
"Honk if you're horny Eat Arbys if you're hungry Die because everything dies Enjoy arbys Nov 14, 2015 ", 
"Don't you love pretending that love is anything more than a random hormonal chemical reaction & ascribing that feeling to Arbys curly fries? Nov 13, 2015 ", 
"What's short, cruel and brutally fucks you in the ass? Life. Also, old Gary who's always hanging out by our dumpsters. Enjoy arbys. Nov 08, 2015 ", 
"RT if you're sitting out by the arbys dumpsters w a warm bottle of gin and a stomach full of the semen of strangers just waiting to die Nov 03, 2015 ", 
"Who has a case of the Mondays? Come down to arbys & contemplate how old you've become & how you've disappointed everyone who once loved you. Nov 02, 2015 ", 
"Being alive sucks. Happy November to all the future dead. Eat a beef n cheddar or something. Whatever. Arbys. Nov 01, 2015 ", 
"For Halloween, Arbys is going as hundreds of thousands of cows, drained of blood, mutilated and turned into garbage. Everything dies. Arbys. Oct 31, 2015 ", 
"Here at Arbys we like to focus on what Halloween is truly about: poisoning children. Happy Halloween from Arbys. Oct 31, 2015 ", 
"Only a few hours left to load up on razorblades and pins for your Halloween candies & plan B pills for your Halloween decisions. Enjoy Arbys Oct 31, 2015 ", 
"Halloween is so scary mommy Why sweetie? The ghosts Oh, Ghosts aren't real, baby. When you die your soul dies & everyone forgets you Arbys Oct 29, 2015 ", 
"As you casually suck your way through the grimy hobo dicks in our mens room, remember: save room for a pumpkin cheesecake shake. Enjoy Arbys Oct 28, 2015 ", 
"Good idea, dipshit. A fitting tribute of rotting flesh doomed to decay & be forgotten. Thanks for enjoying Arbys. https://t.co/IRNS1XNT7s Oct 26, 2015 ", 
"It's time to Meat Your Maker at Arbys. Arbys: like you weren't already gonna die of cancer anyway, you fucking baby. Oct 26, 2015 ", 
"Tonight, toss an Arbys slider in the crib w yer baby, go out & get real high. Trust Arbys. It's not like shit can get any worse for you. Oct 24, 2015 ", 
"Go ahead. Kill that baby hitler if you think it'll make you happy. Arbys doesn't give a shit who you kill. Thanks for enjoying Arbys Oct 23, 2015 ", 
"That awkward moment when your best friend is a dead sliced up pile of bovine flesh and your sentience is an irrelevant fever dream Eat Arbys Oct 22, 2015 ", 
"Today at Arbys, we'll be celebrating back to the future by hurling through time towards the inevitable eternal darkness that awaits us all. Oct 21, 2015 ", 
"When she says \"everything'll be okay\" she's ignoring that you & everyone you've ever known or loved will die in pain. Her too. Enjoy Arbys Oct 20, 2015 ", 
"Joke time, gang! What did God give the blind crippled orphan for his birthday? Cancer. Jk. There's no god. Enjoy arbys. Oct 13, 2015 ", 
"In honor of Columbus Day, we're gonna go completely fuck up the Chipotle on the other side of town. Enjoy Arbys. Oct 12, 2015 ", 
"Now that the novelty of eating McDonald's breakfast at night has worn off, come back to Arbys where time passes, things die & no one cares Oct 07, 2015 ", 
"And on the 7th day, God still didn't exist. Rest up, for tomorrow we die. Enjoy Arbys Oct 04, 2015 ", 
"It's just you and your least favorite child. Come to Arbys. Feed him emulsified beef reformed w meat glue. Watch him slowly die. Arbys. Oct 02, 2015 ", 
"Here at the end of all things, as black smoke plumes beneath your burnt feet & the starving scream for a mercy that never comes, enjoy arbys Oct 01, 2015 ", 
"They found water on Mars. Know what that means? It means that as we suffer & die here there's some useless fucking water on Mars Enjoy Arbys Sep 29, 2015 ", 
"Yo! Shoutout to all the #doomed #losers substituting promiscuity for a self actualized existence this weekend. Die pointlessly. Eat Arbys. Sep 27, 2015 ", 
"Still up from last night? Crawling on the floor looking for any wayward, lost blow? Come on down to Arbys. We're high as balls too. Sep 25, 2015 ", 
"Dear cool pope, There is no God. Anyway, as you traverse this living hell, pls stop into an Arbys. Best, Arbys Sep 23, 2015 ", 
"Ten things you learn eating at arbys: 1. Life is a disappointing, meaningless endeavor 2. Nine other bullshit things Enjoy Arbys. Sep 22, 2015 ", 
"So the British PM fucked a pig? Big deal. Here at Arbys we fuck tens of thousands of pigs every day. Arbys: makin' bacon. Sep 21, 2015 ", 
"In honor of the NFL, this Sunday come to Arbys and shoot your dick off through your sweatpants while surrounded by rapists and criminals. Sep 20, 2015 ", 
"Girl, did you fall from heaven? Bc your mutilated corpse looks like a beef n cheddar swimming in Arby Q sauce splattered on the sidewalk Sep 18, 2015 ", 
"RT if life's an unbearable misery & only the occasional pile of Arbys-brand corpseflesh & lines of cheap cocaine keep you from ending it all Sep 17, 2015 ", 
"Happy 9-11. On this day, like every other day in history, thousands died. In honor of them, please eat at arbys: hunger's 1st responders. Sep 11, 2015 ", 
"Spoiler alert: you will soon die and your flesh will spoil. Enjoy arbys. Sep 10, 2015 ", 
"It's your first time at arbys. What should you get? You should get used to a lifelong creeping dread culminating in your meaningless death Sep 08, 2015 ", 
"Sergio, I need an 8 ball man. The bugs are on me. I swear I'm good for it, bro! Don't FUCK ME LIKE THIS DUDE!!! Er...ahem...eat at arbys. Sep 05, 2015 ", 
"Aaaand the weekend has begun! Enjoy your last quickly dwindling moments on this earth being herpes free, & please enjoy arbys. Sep 04, 2015 ", 
"You are what you eat. You are arbys sliders. You are small & insignificant. You are sliding towards inevitable doom. You satisfy no one. Sep 03, 2015 ", 
"Oh, is it September already? Fascinating bit of stocktaking there, stupid coworker. Eat Arbys. Hurtle towards oblivion. Die. Leave no trace. Sep 02, 2015 ", 
"Saturday morning: Wake up Take off those stained underwear Barf up that semen Exit the arbys bathroom Order a loaded italian Wait for death Aug 29, 2015 ", 
"Each day dozens of you beckon others to gaze into the Arbyss & note that the arbyss gazes back A buzzing of interchangeable flies Eat Arbys Aug 29, 2015 ", 
"Friday night. You sit crying & alone in Arbys, slathered in makeup & scent to mask your revolting decay. you're older than you've ever been. Aug 28, 2015 ", 
"Arbys will no longer bus our tables. You can eat in the filth of those who came before you like the insignificant worms you are. Enjoy Arbys Aug 27, 2015 ", 
"Hey kids! It's hump day, so grab some delicious Arbys, lay back & let this brutal existence relentlessly hump you into a despair laden death Aug 26, 2015 ", 
"Ash blankets a silent, ruined world. The slaves trudge through nuclear winter beneath a black scorched sky to the last Arbys Arbys is closed Aug 22, 2015 ", 
"If you've never shot heroin into a black vein on the top of your dick, then you're not the guy at our bathroom sink right now Enjoy Arbys Aug 20, 2015 ", 
"All minors either get fucked by that guy from @subway, or the relentless persistence of time. Or both. Eat Arbys, for life is bleak. Aug 19, 2015 ", 
"Hate yourself? Hate others? So drunk you can barely stand? Unemployed? Join the Arbys team today and decay w the rest of the doomed losers. Aug 18, 2015 ", 
"Today's horoscope Leo: Your decisions are pointless and your life is ruled by chance. Your existence is galactically irrelevant Eat at Arbys Aug 17, 2015 ", 
"Things to do in your 20s: Fuck a nerd Do drugs Accept that life is a pointless accident Embrace the eternal void of death Eat Arbys Aug 16, 2015 ", 
"Arbys for lunch Arbys for dinner In this fetid hellscape There are no winners Arbys tomorrow Arbys today Nothing's certain But death & decay Aug 15, 2015 ", 
"Even junkies scrape their change together for the delicious taste of Arbys. Arbys: we're just a few half-remembered alleyway blowjobs away Aug 15, 2015 ", 
"Adventure. Heh. Excitement. Heh. Arbys craves not these things. You are reckless, not that Arbys gives a shit. Taste the dark side Eat Arbys Aug 14, 2015 ", 
"As you bleed out in the dust, remember: if some Arby's was strewn around, the carrion birds wouldn't be picking at your eyes yet #Pray4death Aug 14, 2015 ", 
"Line up to die, lugubrious, as the masters herd you towards the killing floor. As go the cows, so go men. There is no God here. Only Arbys. Aug 12, 2015 ", 
"Arbys puts its pants on in the morning just like you: paralyzed by creeping dread as we speed ever closer towards inevitable doom. Eat arbys Aug 11, 2015 ", 
"When daddy says 'never grow up,' tell him you have to grow up so you can die & not be the last person alive in this living hell. Eat Arbys. Aug 10, 2015 ", 
"Mommy, why am I so sick? Shh. Save your energy, baby Does God hate me? Don't be silly, there is no God. Eat your arbys while you still can. Aug 08, 2015 ", 
"10am:Traffic is terrible. You're running out of gin. The girl in the trunk won't stop screaming. She'll be dead soon. So will you. Eat arbys Aug 07, 2015 ", 
"Make no mistake: arbys could give two shits about future maggot-feast john Stewart. Please eat at arbys. We all die alone. Aug 06, 2015 ", 
"2 roads diverged in a wood & I- I took the one less traveled by & I died alone & forgotten with nothing to show for my shitty life Eat arbys Aug 05, 2015 ", 
"How is Lenny kravitz's exposed dick like an arbys beef n cheddar? Both will soon rot into worm riddled, fly encrusted putrescence Eat arbys Aug 04, 2015 ", 
"Roses are black Violets are black Please eat at arbys Go fuck yourself Aug 04, 2015 ", 
"Honey, I need to eat Well, there's food at this rest area ... Oh, it's just arbys Whatever. I'm starving Arbys: whatever. You're starving Aug 04, 2015 ", 
"Are you there God? It's me, 1 of the 7 billion ppl you clearly despise. Anyway, pls don't let the person I fuck tonight have AIDS Eat arbys Aug 02, 2015 ", 
"Before arbys gets sucked into the sun with the rest of the earth and everything you've ever known or loved, please come eat some of our crap Aug 01, 2015 ", 
"If you're stupid and scared to die, try religion. And fuck it, try arbys too. Try whatever you want. Once it goes black you never go back. Jul 31, 2015 ", 
"Arbys: Fast like your brief pointless flash of existence sandwiched between 2 infinite blacknesses. Food, in that technically you can eat it Jul 31, 2015 ", 
"McDonald's has that 'whites only' breakfast sandwich & that kfc mofucker has def owned a slave or 2. arbys don't care. Arbys is just sayin Jul 30, 2015 ", 
"Come to arbys for our new loaded italian. He's shitfaced out by the dumpster giving his cousin herpes in his Camry. Jul 30, 2015 ", 
"Do you know what else kills lions? The relentless persistence of time & the pointless cruelty of life. You'll die the same way. Eat arbys. Jul 29, 2015 ", 
"As you stuff corpse flesh into your revolting body today, consider a starving child. The same void awaits you both. Thx for enjoying arbys. Jul 28, 2015 ", 
"Hi baby. Welcome to earth. You'll start dying right away. your joy will quickly be replaced with shame. Some old man may fuck you. Eat arbys Jul 27, 2015 ", 
"Ever wake up and just want to die? Go ahead. No one will miss you. Arbys. Food. Jul 26, 2015 ", 
"\"Hi! I work at Taco Bell! I'm a total dipshit!\" - total dipshits running taco bell's social media campaign. Eat arbys. Die. Be forgotten. Jul 25, 2015 ", 
"Come to arbys where the only shooting is done with dirty needles in the men's room. Or don't come. Who fucking cares? Life sucks. Jul 24, 2015 ", 
"You've shit your pants again. The Doors are on the radio. The gin's nearly gone. It's almost noon. Stop by arbys. No one is here. Die alone. Jul 23, 2015 ", 
"What should our next menu item be? Pizza? Tacos? Bags of blow? Fettuccini? Just kidding. Arbys isn't interested in your opinion. Enjoy arbys Jul 22, 2015 ", 
"We're playing john Mayer in our dining rooms. Jul 20, 2015 ", 
"Drive: Drunk High While getting a beej Through arbys Into a group of revelers Nothing matters. Hit pedestrians. Namaste. Jul 19, 2015 ", 
"Never forget who you are: a tiny speck on an insignificant rock hurtling through a void. May as well fuck some strangers this weekend. Arbys Jul 17, 2015 ", 
"It's 3 am. You awake in a panic. You're wasting your life? You're alone? relax. You're totally insignificant & you'll die soon. Enjoy arbys. Jul 16, 2015 ", 
"Vote Trump. stockpile guns. lick a turd fresh from the toilet. Drive hammered. Eat arbys. Put a GI Joe up your ass. Arbys: Who gives a shit? Jul 15, 2015 ", 
"So, 50 cent is broke, eh? In other news, everything you've ever known or loved will die or be cataclysmically destroyed. Enjoy arbys Jul 13, 2015 ", 
"How's your weekend? Just kidding. Arbys couldn't give 2 shits. Please eat at arbys. Jul 11, 2015 ", 
"Thank god that flag is coming down. If only there was a god. If only putting some dumb flag in the trash could ease life's misery. Eat Arbys Jul 10, 2015 ", 
"As the NYSE, United, & WSJ all burn, remember: Arbys now serves brown sugar bacon sandwiches because we truly don't give a shit Jul 08, 2015 ", 
"Hey @SUBWAY, where's your God now? Your first mistake was believing in anything. Life is vile. Eat arbys. Die quickly. Escape to blackness Jul 07, 2015 ", 
"Arbys #mancrushmonday goes out to man, crushed by the weight and cruelty of an indifferent universe. You'll never be this young again. Jul 06, 2015 ", 
"Today, celebrate a crumbling empire by shoveling fistfuls of Arbys meat into your bloated face and then drunkenly blowing off your toe. #usa Jul 04, 2015 ", 
"Put something special in you this weekend, America: some Arbys, some cocaine, scotch, random schlongs. It doesn't matter. Nothing matters. Jul 03, 2015 ", 
"This Canada day, as Jim Carrey dictates what you should do to your children, remember Jim & all children will die either way. Enjoy Arbys. Jul 01, 2015 ", 
"Draw the blinds. shut out the sun. Cry. The pile of meat has been on the table for weeks. Just eat it & go back to bed. Arbys: edible. Jul 01, 2015 ", 
"Just like Ben affleck and Jennifer garner's doomed union, you too are something arbys doesn't give a shit about. Pls continue enjoying arbys Jun 30, 2015 ", 
"Welcome to Arbys. Can I help you? JK. No one can. Which dead animal would you like to waste a few minutes of your useless life eating today? Jun 30, 2015 ", 
"Best case scenario: Gay or straight, your marriage ends when the person you love most dies and leaves you to rot in solitude. Eat at Arbys. Jun 26, 2015 ", 
"Tonight, why not try our succulent roast bullshit piled high atop our artesian crap with a side of garbage? Arbys: nothing matters Jun 24, 2015 ", 
"Yo, it's summer & life's a beach. Covered in corpses on the edge of a scorched continent on a burning world in a cruel universe. Enjoy Arbys Jun 24, 2015 ", 
"As everyone you've ever loved decays, becomes ossified in filth or burns in the sun, distract yourself with some fucking Arbys. Whatever. Jun 23, 2015 ", 
"Arbys tweets at inappropriate times. Why? Because arby doesn't give a shit. Arbys: tweeting late as shit on a Monday. Jun 23, 2015 ", 
"As you tell your dead father you love him today, remember, he can't hear you because he's dead and there's no god. Please enjoy Arbys. Jun 21, 2015 ", 
"Shout out to all the dads sleeping in today because they've abandoned their families. Arbys: fucking your mom & running out for some smokes Jun 21, 2015 ", 
"Hey you pathetic, greasy bag of rancid meat, eat at Arbys. Jun 20, 2015 ", 
"This weekend, drunkenly shit on your neighbor's porch. Arbys: why not? Jun 19, 2015 ", 
"Arbys also identifies as black: the eternal blackness that eventually engulfs us all. Arbys: sandwiches in the abyss. Jun 17, 2015 ", 
"Stare at the spreadsheet Your waterbottle is full of gin Your kids are getting old, they no longer love you. Arbys: we don't love you either Jun 15, 2015 ", 
"Is it Monday again? Oh good. Toil, cry, drink yourself into sweaty oblivion. Die a little more each day. Eat at Arbys. Repeat. Jun 15, 2015 ", 
"So, church is a total waste of time, right? Full of dorks and losers. Also there's no god. Arbys: let's get high Jun 14, 2015 ", 
"That awkward moment when you're a lone fever dream in an ectoplasmic sea of electrons and emptiness. Arbys: Bae and beyond. Jun 13, 2015 ", 
"Why not wash down that regrettable semen-of-the-coke-dealer taste in your mouth with a little Arbys? Arbys: no one here cares what you do. Jun 13, 2015 ", 
"Here's a little late night inspiration: you're ugly, your one night stand will notice your fat rolls and you'll die alone. Arbys: remorse Jun 13, 2015 ", 
"Slather yourself in makeup. Perfume off that shit smell. Curate the illusion you're not decaying right there on the dancefloor Arbys: nights Jun 12, 2015 ", 
"It's the weekend! Know what that means? That's right! You're closer to death than you've ever been before. Arbys: serving food Jun 12, 2015 ", 
"We no longer care if our employees wash their hands. Work at Arbys and enjoy the illusion of freedom in enslaved doom. Arbys: a place to die Jun 11, 2015 ", 
"The only way out of this nightmare is the sweet release of death, so fuck it. have another sandwich, fatty. Arbys: to your nadir and beyond Jun 10, 2015 ", 
"Hey @Starbucks, go fuck yourself. Please eat at Arbys. Jun 09, 2015 ", 
"Step 1: go to Arbys Step 2: order potato cakes Step 3: delude yourself into thinking your life is anything more than a meaningless accident. Jun 09, 2015 ", 
"Why you're alone: 1. Life's an illusion & sentience exists in a void populated only by your own madness 2. You're a loser Arbys: lunch for 1 Jun 08, 2015 ", 
"Hey, you know what else produces the same shitty, doomed, meat based joke over and over? human vaginas. Arbys: it's curtains for all of us. Jun 07, 2015 ", 
"Congratulations to future glue-stick American pharaoh for doing something completely pointless very fast. Arbys: racing towards the abyss Jun 07, 2015 ", 
"S-A-T-U-R-D-A-Y! NIGHT! Statistically, a few of you will be dead by morning. Please enjoy Arbys. Jun 06, 2015 ", 
"Today at Arbys, just do some lines on the counter. Nobody who works here cares at all. Arbys:vaguely like studio 54 Jun 05, 2015 ", 
"I've wanted to die. I've wanted to kill. I'm going to Arbys. Maybe I will. Jun 04, 2015 ", 
"Today why not bring some of that cash that you made sucking off truckers down to Arbys for a different kinda mouthful? Arbys: flesh peddlers Jun 03, 2015 ", 
"So hungover you'd rather be dead? Hang in there. You'll be dead very soon. Arbys: Arbys. Jun 02, 2015 ", 
"Face down, ass up, that's the way the dead junkie was found in the men's room. Arbys: it's Monday. Jun 01, 2015 ", 
"You probably won't die tonight, but if you do, who cares? Arbys: fuck you May 31, 2015 ", 
"We all did some pretty regrettable shit last night. You especially. She was your cousin. Arbys: in the room, not judging. May 31, 2015 ", 
"As you chug whiskey from your coffee mug during your daughter's soccer game, remember: you're sleeping in the dumpster behind Arbys tonight May 30, 2015 ", 
"This weekend, why wine and dine her and not get laid when you can eat at Arbys alone then sit in your garage with the car on? Arbys: food May 29, 2015 ", 
"Hey, you fucking dipshit. Eat at Arbys. May 29, 2015 ", 
"What's it, Monday? Wednesday? Arbys been wasted for days. Don't judge Arbys. We're all gonna die, so fuck it. Arbys: get annihilated with us May 28, 2015 ", 
"What will they say at your funeral? You were wise? Kind? Lonely? A pervert? It's all the same where you're going. Arbys: where you're going. May 28, 2015 ", 
"Having a rough day? Hate your job? Kids dying? Wanna end it all? Afraid of the infinite blackness that awaits you? No one cares. Enjoy Arbys May 27, 2015 ", 
"You're born. You need: shelter Arbys sleep sex to defecate. You die & vanish. Everyone forgets you. Arbys: right up there with shitting May 26, 2015 ", 
"To those brave men who died on the beaches in Normandy or the viet nam ratholes: no one even remembers your names. Arbys: life is bleak. May 25, 2015 ", 
"This Memorial Day, leave your syphilis riddled corpse on some foreign shore. Arbys: no funeral. May 25, 2015 ", 
"Shoot up. Head down to Arbys. Order some poppers. Suck a dick or two. Sleep in our bathroom stalls. Arbys: let us throw you away May 24, 2015 ", 
"And those times when there were only one set of footprints in the sand, that's when uh...whatever dumb shit you believe. Arbys: you're alone May 23, 2015 ", 
"Who cares if you're ugly? Not Arbys. Arbys serves ugly ass motherfuckers like you every day. Arbys: for people like you. May 23, 2015 ", 
"How many kids do you have? 19 and counting? None? Either way, come to Arbys: molest your tastebuds. May 22, 2015 ", 
"Appealing to children, prizes, the afterlife, deluxe ingredients, God, copyright law: Arbys believes not in these things. Arbys: just do it May 22, 2015 ", 
"Is it worth it to be born into misery, & die alone for that brief chance to love? No. It's exactly the same as never being born. Enjoy Arbys May 21, 2015 ", 
"She's dead, chief. Covered in blood &...horsey sauce? Life's brutal, Johnson. Let's go to Arbys. Arbys: whatever gets you through the day May 21, 2015 ", 
"This living hell got me like *washes down handful of pills with bleach, steps to ledge, finishes Reuben, jumps* Arbys: #engaging #socially May 20, 2015 ", 
"He's covered in flies, laying in a pool of fetid urine. He's begging you for help, starving. Arbys: step over him & come on in. May 20, 2015 ", 
"You're alone. You're actively killing yourself with alcohol. Your breath smells of Arbys. Don Henley is on the radio. Arbys: Pray for death. May 19, 2015 ", 
"Monday's terrible Tuesday's the worst Wednesday's the day I hated most first Thursday can blow me Friday can too Lets go to Arbys Then screw May 18, 2015 ", 
"It's Monday. Drive drunk. Kill bums. Eat Arbys. Fuck strangers. Burn shit. Punch grandmas. Steal. Get high. Die alone. Arbys: whatever. May 18, 2015 ", 
"Invest in skulls. Worship garbage. Consume smokehouse briskets until you burst. Die lonely. Arbys: no one will miss you. May 17, 2015 ", 
"You know what fucking sucks? Everything. Decay at Arbys: a waking grave. May 17, 2015 ", 
"Give a man an Arbys sandwich, he eats for a day. Teach him to slaughter, & he dies bloody & alone in darkness just like he would have anyway May 17, 2015 ", 
"Your parents don't love you your children will die Come eat Arbys It's best if yer high Drink the poison Gargle the flesh Arbys: then death May 15, 2015 ", 
"Fuck nihilism. Fuck Arbys. Fuck everything else. Fuck you. Please eat at Arbys. There's no god. May 15, 2015 ", 
"🎶Life is a drivethru I been a-dying all night long Get me some Arbys to kill the illusion of right & wrong Arbys: stuck in your head & colon May 14, 2015 ", 
"Your pathetic gentials cower beneath your distended gut as you drive naked through this shitty maze of filth. Arbys: 500 yards from a school May 14, 2015 ", 
"Put my corpse in a canoe. push it through the drive thru as a lit arrow sets my rotting flesh aflame. Curse the godless sky Bury me at Arbys May 13, 2015 ", 
"How come you park in a driveway but die with your dreams unfulfilled and then are quickly forgotten? Arbys: die in the driveway. May 12, 2015 ", 
"This Monday, shoot your hunger in the face with a little Arbys! May 11, 2015 ", 
"What do Jesus, the Easter bunny & aliens have in common? If you answered 'my life is an irrelevant accident,' you're correct! Enjoy Arbys. May 11, 2015 ", 
"Your looks will fade, bae. Go as ham as you want, for the abyss ensnares us all. Arbys: you're literally dying. You literally can't even. May 10, 2015 ", 
"Your mom had such high hopes for you. For Mother's Day, buy her Arbys & pretend she didn't just crap out deluded garbage all those years ago May 10, 2015 ", 
"This morning, why not wash that Plan B pill with a little plan A? Arbys: what's one more bad decision? May 09, 2015 ", 
"This weekend, enjoy Arbys with some fava beans and a nice chianti. Arbys: we can smell your cunt. May 08, 2015 ", 
"Behind the veil, there's nothing. On this side of the veil, nothing. There's no veil. There are no sides. Arbys: we are so high right now. May 08, 2015 ", 
"You've been chained in the basement for weeks, covered in filth. You gave up long ago. Arbys meat litters the floor. Arbys: pray for the end May 07, 2015 ", 
"As you draw your last breath & feel that final Arbys chicken cordon bleu soothe your death rattle, remember: you've wasted your life. May 07, 2015 ", 
"Well, if it isn't the hamburglar. Hey, McDonald's: really nice try. Arbys: burgle this ham, motherfucker. There's only one way out. May 06, 2015 ", 
"Come on down to Arbys: a place where no one knows who you are or cares what happened at that rest area last week. Arbys: eat your sins. May 06, 2015 ", 
"This Cinco De Mayo, as you desperately chug tequila to muster the courage to attempt sex with a vomit covered stranger, think Arbys. Ole! May 05, 2015 ", 
"Why not take a casual break from your daily recreational cocaine use to purchase an Arbys sandwich and look at it for a while. Arbys: items May 04, 2015 ", 
"May the eternal darkness of infinite nothingness be with you. These aren't the sandwiches you're looking for. Please go to Arbys instead. May 04, 2015 ", 
"A woman beater made 83k per second to pummel a nerd & you think there's a god or justice or a plan? Arbys: don't be stupid. Life is cruel. May 03, 2015 ", 
"Kentucky derby day! Run in a circle! If you falter we'll melt you into glue. What an apt metaphor for humanity's fate. Pls eat arbys today May 02, 2015 ", 
"Tonight, as you cry your way through your regrettable one night stand, remember that tomorrow at arbys, no one will care what you've done. May 01, 2015 ", 
"Mayday! Mayday! We're born to struggle & die & life is an accident. Please enjoy Arbys as you approach your dignity-free respite from toil May 01, 2015 ", 
"How many selfies of yer junk didja take today? Rad! Keep looking at your own dick while earth burns around you. Arbys: rappin w millennials Apr 30, 2015 ", 
"This morning, as you casually shit into your sweatpants on the city bus, take a long, reflective drink of gin & anticipate lunching at Arbys Apr 30, 2015 ", 
"Arbys catered the funeral. No one came. Flies swarmed the forgotten corpse & the pile of beef n cheddars. Arbys: same shit, different flies. Apr 29, 2015 ", 
"Mommy, am I dying? Yes baby, everyone dies Is it because Im so sick? Well, we aren't in this hospital for the food. Arbys: come for the food Apr 29, 2015 ", 
"Try Arbys turkey gyro, now for a limited time. What else do you have going for you in this fetid shitscape? Arbys: it'll all be over soon. Apr 28, 2015 ", 
"For lunch today, why not wash down your arbys with some whiskey & pills. Take the day off work. Just start walking. It's a good day to die. Apr 28, 2015 ", 
"Sometimes you're the one getting fucked in the ass by a cold indifferent universe & sometimes you're still that but hungry. Arbys: food porn Apr 27, 2015 ", 
"My life: an illusion My job: a distraction from inevitable doom My car: Honda, mid 90's My god: death My universe: a void My meats: Arbys Apr 27, 2015 ", 
"We get this a lot: Arby's made me feel like shit. So? You're less than shit. You're a nothing adrift in a void. Pls continue to eat at Arbys Apr 26, 2015 ", 
"What dumb bullshit did you do this weekend? Did it go well with Arbys curly fries? Oh really? Fascinating. Arbys: a social media presence. Apr 26, 2015 ", 
"Been dying for the weekend? At Arbys it's always the weekend because time is a meaningless abstraction even as death creeps closer every day Apr 25, 2015 ", 
"You've spent your best years doing things you don't love, combating hating yourself with drugs & shameful drunk orgasms. Arbys: life sucks. Apr 24, 2015 ", 
"When our new line of limited time sandwiches came out, the world said 'Arbys! Who let the gods out?' Answer: there are no gods. Eat up & die Apr 24, 2015 ", 
"AR you gonna die? Only to discover that there is no God or afterlife? BY golly, you are. Arbys: spelling shit out for you since 1964 Apr 23, 2015 ", 
"Happy earth day. Ignore for a moment that the earth is the cause of all your suffering, and that in turn we destroy her, & just go to Arbys. Apr 22, 2015 ", 
"You think YOU'VE got problems? Pfft. You do. Love is an illusion and the brutal persistence of time will destroy you. Arbys: die full. Apr 21, 2015 ", 
"It's drugs day. Enjoy your disgusting bong and your parents' basement. I bet you have some Arbys down there, Don'tcha, big boy. Sure ya do. Apr 20, 2015 ", 
"Monday is the shittiest day so go to Arbys. no one is here. drink scotch out of a soda cup and ponder ending it all. no one will see you die Apr 20, 2015 ", 
"Arbys: we don't care at all. Just eat our shit and get on with your meaningless existence. Arbys: a place you may go. Apr 19, 2015 ", 
"No matter how beautiful she is, somewhere out there there's a guy who's sick & gonna die & rot just like her, & you. Til then, enjoy Arbys. Apr 19, 2015 ", 
"How cool would it be to die? No more of that horrible mom telling you to leave the basement. She'd mourn. Now who's a loser, mom? Eat Arbys. Apr 19, 2015 ", 
"Its a beautiful day to lay in bed w the blinds drawn & hide from this hideous pigfuck nightmare life. If you do venture out, pls go to arbys Apr 18, 2015 ", 
"What's up this weekend? Pissing away the few precious moments you have left? You'll never be this young again. Piss that youth away at Arbys Apr 17, 2015 ", 
"Good morning slaves. It's a good day to die, or to be dead. Whatever. it's all the same. Join us at arbys. Eat the dead. Apr 16, 2015 ", 
"There are 3 certainties: taxes, death and that Arbys will sell you flesh. Arbys: happy tax day. there is only one way out. Apr 15, 2015 ", 
"Ever sniff so much glue that you briefly feel a joyous burst of hope? When that ends & you feel eternal doom staring you down, think Arbys. Apr 15, 2015 ", 
"Feeling blue? Cheer up! You'll be dead soon enough, in an unfeeling blackness. Meanwhile, there's Arbys. Please eat at Arbys. Apr 14, 2015 ", 
"The kids are buried in satanic patterns in his yard. What a waste of time. Satan doesn't give a shit about patterns or exist. Arbys: meals. Apr 13, 2015 ", 
"Thank god it's Monday. Before you ready the noose and kick the chair in the breakroom from under you, why not get some Arbys for the team? Apr 13, 2015 ", 
"Nobody wins the game of roast beef. House Manager, House Cashier, House Stoned Customer, House Curly Fry: they all perish. arbys is coming. Apr 12, 2015 ", 
"Cry. Go ahead and cry. Nana ain't coming back. Neither is fluffy. Go to Arbys and eat some hillbilly boy's pet cow. The universe is cruel. Apr 12, 2015 ", 
"Thirsty? Arbys offers Pepsi products! Hungry? Enjoy an Arbys limited time gyro. Hate yourself? We all do. Die & vanish. You won't be missed. Apr 11, 2015 ", 
"You know where you are?! You at Arbys baby! You gonna DIIIIIIIIIIIIIIIE!!!!!! Arbys: the jungle. The horror. The meats. Apr 11, 2015 ", 
"Your blood flows down the pavement, towards your half eaten french dip. It won't be long now. Arbys: Once it goes black you never come back. Apr 10, 2015 ", 
"We've all performed oral sex on our drug dealers through tears out of desperation, for this world is a dark place. Arbys: get the taste out Apr 10, 2015 ", 
"Release the emergency brake. Lock the doors. Watch the car idle down the pier. Ignore the screams. That car is also full of delicious arbys. Apr 09, 2015 ", 
"Grease erodes your Arbys bag. It rips. curly fries litterr the sidewalk. kneel & greedily devour them, ignoring passersby. Arbys: no dignity Apr 09, 2015 ", 
"A-R-B-Y's! Every living creature dies! Arbys! Arbys! Goooooooo, Arbys! Apr 08, 2015 ", 
"Like a lone drifter who rolls into town at sundown, shoots up behind your garage and sleeps under your porch, arbys is waiting for you today Apr 08, 2015 ", 
"There is no God. There is no heaven. There is no hell. There is no Dana. There is no Zuul. There is only Arbys. Try the Reuben. Then die. Apr 07, 2015 ", 
"An empty vodka bottle floats in the pool near his bloated corpse & the remains of his Arbys crispy chicken sandwich. Finish it. No one cares Apr 07, 2015 ", 
"I watch my championship college basketball the same way I eat my arbys potato cakes: with the nagging knowledge that soon we'll all be dead. Apr 07, 2015 ", 
"Someday you will die. Someday soon after that, no one will remember you were ever here. Arbys: somebody's got a case of the Mondays. Apr 06, 2015 ", 
"Throw away an arbys Reuben. 3 days later, fish it out of the garbage & let it save you. Die and be forgotten. Arbys: Easter n shit. Apr 05, 2015 ", 
"Happy Easter! Today only, we have Arby-Q rabbit hoagies. JK. Your deity is a crutch and a myth. Arbys: same old shit, then death. Apr 05, 2015 ", 
"Every member of every final four team will die alone and fade into eternal nothingness. We have limited time gyros. Arbys: sports. Apr 05, 2015 ", 
"Pestilence Mass death The earth is devoured by the sun Eternal, indifferent blackness #FinalFour Please continue eating at arbys Apr 04, 2015 ", 
"Try an arbys angus philly today. Or just buy it & throw it away. Or hell, fuck it. Arbys: we don't give a shit if you fuck our sandwiches. Apr 04, 2015 ", 
"Arbys wrappers litter the car. The doors won't unlock. 'Mister, where are you taking me?' you ask. He's silent. Arbys: your last meal. Apr 04, 2015 ", 
"Thank GOOD It's Friday. Drag your cross to arbys today, enjoy a french dip and die believing whatever you want. Arbys: there is no God. Apr 03, 2015 ", 
"I want arbys in the streets & a cowboy in the sheets. The cowboy is you. You're dead. The arbys is closed. everyone's dead. This is the end. Apr 03, 2015 ", 
"There are 2 kinds of people in the world: pathetic nobodies, and great heroes who die & are forgotten just the same. enjoy Arbys Apr 02, 2015 ", 
"*eats arbys curly fries at funeral *grieving widow scowls *offers her a fry *whispers 'the soul is a fallacy' Arbys: not bullshitting anyone Apr 02, 2015 ", 
"Arbys would like to announce our \"please don't get high and come to arbys\" initiative. April fools! Life is pain, do whatever you gotta do. Apr 01, 2015 ", 
"Life goes better with arbys! April fools! Life goes quickly and your choices are irrelevant. Please enjoy arbys. Apr 01, 2015 ", 
"Rip it to shreds. Put it on a bun. Slather it in horsey sauce. Watch them line up to gorge. Feeding pigs to pigs. Arbys: a flat circle. Mar 31, 2015 ", 
"Enjoy the unbelievable electric rush of interacting w arbys online? Love dipping our #crap in our other #shit? Who cares? Arbys: fuck this. Mar 31, 2015 ", 
"Roast bieber. slather him in horsey sauce. He wants it. His soul is tonight's delicious arbukakke. Enjoy arbys. Die laughing. No one cares. Mar 31, 2015 ", 
"Every single person who eats at McDonald's will die. Please eat at arbys. Mar 30, 2015 ", 
"Pick up arbys Dine at home Beef n cheddar On the throne In the dark Nobody's home To hear you when You die alone Thanks for enjoying arbys Mar 30, 2015 ", 
"Ever wake up and just wanna die? May as well be today. Arbys: a restaurant. Mar 29, 2015 ", 
"Ever have 1 of those days where life doesn't even seem worth living? Head to arbys & enjoy our chicken cordon bleu w the rest of the damned Mar 29, 2015 ", 
"What's humanity but a random experiment in cruelty? What's life but a parade to the grave? What's Arbys snack'N save menu but a great value? Mar 28, 2015 ", 
"Your sign says lots about your ideal Arbys sandwich. for example, if you're a Virgo, you'll die alone. That goes for all signs. Enjoy Arbys Mar 27, 2015 ", 
"Longest dinner ever. Grandpa won't shut up about viet nam. If only I was at Arbys. Or dead. Either way. Whatever. Arbys: family is the worst Mar 26, 2015 ", 
"Sure, KFC did that no-bun thing. Now try our thin-sliced, worthless life of pain sandwiched between 2 godless eternities. Arbys: going big. Mar 26, 2015 ", 
"The whole village is dead. There is no God to mourn them. The few ragged survivors feed on the rotting corpses. Shoulda gone to Arbys! Mar 26, 2015 ", 
"Maybe that kid who quit One Direction could get a job with us. JK! There's only One Direction: into blackness. Arbys: one direction, no hope Mar 25, 2015 ", 
"Running out for a pack of smokes was for your old man's generation. Today, run out for a beef n cheddar. Arbys: leave 'em all behind forever Mar 24, 2015 ", 
"What's on your bucket list? Skydiving? Swimming w Dolphins? Some fucking sandwich? Whatever. Arbys: we got your fucking sandwich right here. Mar 24, 2015 ", 
"True hell is watching yourself age & realizing that everything that anyone ever loved about you no longer even exists. Please eat at Arbys. Mar 23, 2015 ", 
"Why cook when you can go to Arbys? Why walk when you can drive? Why work when you can drink gin in your bed? Arbys: why not? Mar 22, 2015 ", 
"When the inevitable comes and they walk the earth, flesh will be the only relevant currency. Arbys: your bank for your future. Mar 22, 2015 ", 
"You finished the pills at sunrise. Now, all the scotch is gone. It's almost noon. Arbys: your last stop on your way to the bridge. Mar 21, 2015 ", 
"It's almost the weekend! Time to drink yourself into oblivion & stave off the inevitability of eternal blackness w gross sex & yummy Arbys! Mar 20, 2015 ", 
"Arbys was drunk when Arbys made that last tweet. Arbys wasn't even trying. Trying is pointless. the end result is the same. See last tweet. Mar 20, 2015 ", 
"Arbys: You will die. Mar 20, 2015 ", 
"March to Arbys. Unleash your Madness. Go nuts. Play in fire. Drive drunk. no one cares if you die. Arbys: begin the elimination round. Mar 19, 2015 ", 
"You've done some horrible, unspeakable things. Arbys doesn't care. Nothing matters. Enjoy horsey sauce. Arbys: put the lotion in the basket Mar 18, 2015 ", 
"Enjoy Arby's today, for death comes quickly and there are no Arbys chicken cordon bleu sandwiches in the abyss. Arbys: it's now or never. Mar 18, 2015 ", 
"We, like @Starbucks would like to encourage everyone to #RaceTogether towards the infinite void of doom that sees neither color nor creed. Mar 17, 2015 ", 
"Happy st Patrick's day: fun reminder: time erases all histories and legacies, even if you're Irish. Arbys: adrift in a godless eternity. Mar 17, 2015 ", 
"It's not drinking alone if your whiskey's in an Arbys cup, it's still breakfast time, the lights are off, & your old pal Reuben is there. Mar 16, 2015 ", 
"Wow, church was a waste of time, considering that there's no god and life is a cosmic, irrelevant accident. Let's go to Arbys. Mar 15, 2015 ", 
"Welcome to Arbys. what can I get you today? Oh, nothing. Thanks. Okay, coming right up. That only comes in \"eternal,\" is that okay? Mar 15, 2015 ", 
"Hey you drunk pigs, why not barf up a little Arbys this st Patrick's day before your dumb fights and regrettable sex. Arbys: seasonal shit. Mar 14, 2015 ", 
"There's no God It's Friday...eat at Arbys and enjoy the few weekends you have left. Mar 13, 2015 ", 
"*Mommy? What happens when we die? *We all turn off forever. *Then why are we here? *just enjoy your delicious Arbys. The end comes quickly. Mar 13, 2015 ", 
"Q: What's long, hard, black, and fucks you in the ass? A: The abysmal void of nothingness that awaits us all. Arbys: we do some jokes. Mar 12, 2015 ", 
"Life is a fleeting flash of dawn. Death is merely a return to the eternal void. Spend your flash of dawn enjoying breakfast at Arbys today. Mar 12, 2015 ", 
"The stars at night are already long dead...something something Texas. Arbys: local flavor. Mar 12, 2015 ", 
"Wallow in filth. Follow the herd. Enjoy a jr ham & cheddar. march willingly to the killing floor & escape into the black. Arbys: Be the pig. Mar 11, 2015 ", 
"She feeds her kids handfuls of dirt to try & kill their hunger pains. A world away he's crammed w ham. They all die. Arbys: we got the meats Mar 11, 2015 ", 
"Sure, KFC ditched the bun, but at Arbys we're just handing out handfuls of meat and doing a sauce trough. Arbys: who fucking cares? Mar 10, 2015 ", 
"To do list: Get to Arbys Order the Rachel Get some curly fries, son Enjoy Arbys Die alone in a world that hates you Specify 'no funeral' Mar 09, 2015 ", 
"Happy Monday. Celebrate w lunch at Arbys, dinner alone in your car, & a life of wasted potential & regrets. Arbys: why even get out of bed? Mar 09, 2015 ", 
"You know that depression that eats at your soul & won't go away? When you feel Iike no one cares about your pathetic being, remember: Arbys Mar 08, 2015 ", 
"He died doing what he loved: nothing. Please enjoy Arbys: a restaurant. Mar 08, 2015 ", 
"As you watch porn in the dark and ponder the fact that no one loves you, think Arbys, a weekend respite from your pointless, living hell. Mar 07, 2015 ", 
"Enjoy these limited time offers: the illusion that your existence matters, and our yummy jalapeño hushpuppies. Arbys: it's the weekend. Mar 07, 2015 ", 
"The dashboard clock says 9 am. He takes 11 more pills. One more bite of his delicious Arbys french dip. He leaves no legacy. Nothing. Arbys. Mar 06, 2015 ", 
"Hey#teens. Skate and die. And quench that thirst w a kickass mtn dew and wash it down with a dope beef n cheddar. Arbys: gleaming the void Mar 06, 2015 ", 
"Hey gang! Introducing our new Rachel sandwich &just like the girl from work, this Rachel doesn't love you either. Arbys: love doesn't exist Mar 05, 2015 ", 
"I scream. You scream. We all scream because life is misery. Arbys: we probably offer some kind of ice cream themed shit. Mar 05, 2015 ", 
"Nothing goes better with a yummy Arbys breakfast sandwich than a nice pull from that pint of gin you keep in your glove box. Arbys: fuck it. Mar 05, 2015 ", 
"The last person left alive on earth can eat all the curly fries they want, & they'll be no lonelier than we all are today. Arbycolypse now. Mar 04, 2015 ", 
"WHAT DO WE WANT? ARBYS! actually desires are a waste of a life that is, itself, pointless. WHEN DO WE WANT IT? Time's a fallacy. Await doom Mar 04, 2015 ", 
"Naive teen: there's nothing better than drugs! Arbys: have you tried our curly fries yet? Teen: yup. Arbys: oh, do drugs then. Life sucks. Mar 04, 2015 ", 
"Eat the Arbys. The lights are off. You're alone. There's sauce on your chin.No one will cry when you die. Arbys: you're wearing sweatpants. Mar 03, 2015 ", 
"Another great Yelp review: \"I was born into a meaningless world of pain. Nothing matters. Soon I will die. I eat at Arbys. Good sandwiches\" Mar 03, 2015 ", 
"It's Monday, but don't let that get you down! Head to arbys, get one of our beef n cheddars & eat it alone in the dark like you do everyday Mar 02, 2015 ", 
"The death squads are roaming the village. Families cry in silence, praying for a quick end. Still hate Arbys? Arbys: get over yourself & eat Mar 02, 2015 ", 
"You'll die if you don't eat. You'll die if you do. Arbys: we have some sandwiches & shit. Your fate is sealed. Die. Be full when you do. Mar 01, 2015 ", 
"Q: What would the grim reaper order at Arbys? A: trick question, life is an accident and your mythology is just pablum. Eat at Arbys. Feb 28, 2015 ", 
"Bro, let's meet down at the Arbys and ponder the galactic futility of even making banal plans such as these over some potato cakes #teens Feb 28, 2015 ", 
"How many shots of Arby sauce can you take in one sitting? How about horsey sauce? Jim Beam? Cow blood? Bullets? Arbys: pick your poison. Feb 27, 2015 ", 
"Bad hair? Ugly? No one loves you? Our sandwiches are made of mutilated dead things. Arbys: get over yourself & enjoy a yummy angus philly. Feb 26, 2015 ", 
"Get this: those two llamas...you know where they're running to? That's right: their inevitable doom. Arbys: no gods. no llamas. Feb 26, 2015 ", 
"The car is on. The garage door's closed. The kids are napping. Open the garage. drive to Arbys. Try our new turkey Rachel. Arbys: Die later. Feb 26, 2015 ", 
"Kfc now has edible coffee cups? Pfft. All cups are technically edible. All innovation is futile. All souls are worthless. Arbys: edible. Feb 25, 2015 ", 
"some of our customers recently expressed dissatisfaction with their Arbys experience. Makes sense. Life is hell. Arbys: welcome to earth. Feb 25, 2015 ", 
"Like a burrito made by Mengele, Arbys monstrous, godless aberration the turkey & Swiss wrap is delicious testament to a cruel empty universe Feb 25, 2015 ", 
"WHO BRING THAT RUCKUS? -ARBYS! WHO BE SPRAYIN THAT HORSEY SAUCE? -ARBYS! AND WHO GON' DIE ALONE IN A COLD UNIVERSE? All of us. Enjoy Arbys. Feb 24, 2015 ", 
"His blood stained the sand. Her tears fell upon his face. she whispered 'God waits for you.' He moaned 'No God, only Arbys' and he was gone Feb 24, 2015 ", 
"Now for only $12, eat something. Die forgotten and alone. Be too dead to experience the end of the earth & universe. The end: Only at arbys. Feb 24, 2015 ", 
"Hide from your horrible family at arbys. Abandon your worthless soul in our delicious french dip. Arbys: you were never here. vanish with us Feb 23, 2015 ", 
"Arbys cows raised on arbys farms, sliced up by arbys employees. thrown away, uneaten by arbys customers. Arbys: life has no purpose Feb 23, 2015 ", 
"Tonight, fake looking humans worship each other for their beauty and artifice. Tomorrow, at least one of you will be dead. Arbys: whatever. Feb 23, 2015 ", 
"First, I'd like to thank god: a meaningless abstraction as absurd as your dead dreams. Next thanks to Arbys Reuben. Best fuckin Reuben, yo. Feb 23, 2015 ", 
"Which Arbys sandwich most resembles Liam Neeson? Who cares? He'll die soon and the earth will be eaten by the sun. #Oscars Feb 23, 2015 ", 
"McDonalds: narcs to yer mom when you're drunk Burger King: worthless poser Taco Bell: shits at your house Arbys: ready to kill. Ready to die Feb 22, 2015 ", 
"There's no Arbys in heaven because there is no heaven. However, there are Arbys in hell because this is hell. Arbys: welcome to hell. Feb 22, 2015 ", 
"Yo, Arbys teens! What rules most? 1st kiss? Gettin that license? Tryin curly fries? Realizin that no matter what, u n all yer friends die? Feb 21, 2015 ", 
"The pawnbroker is old & cruel. She has no friends. kill her. only your guilty conscience could betray you. Arbys: surrender to your desires Feb 21, 2015 ", 
"A soiled, bare mattress on the floor. A naked bulb sways in the gloom. Arby's wrappers, strewn everywhere. Arbys: it's come to this. Feb 20, 2015 ", 
"Can this pointlessness get any more depressing than it already is? Arbys: a delicious sandwich store embedded in a living hell. Try the food Feb 19, 2015 ", 
"We all sin. We all destroy. We all come to naked covered in horsey sauce & have to call a friend to help dispose of a body. Arbys: a friend. Feb 18, 2015 ", 
"Arbys: when this nightmare ends, we'll be gone too. Feb 18, 2015 ", 
"Ever sit in your dark basement all day & night for days, just peeing in Gatorade bottles and wishing your mom would bring you some arbys? Feb 18, 2015 ", 
"Kill for the arbys reuben. Die for the beef n cheddar. Decimate a culture for the angus philly. Arbys: crusading into the abyss since 1965 Feb 17, 2015 ", 
"Losers eat at McDonald's. Losers eat at Burger King. Losers eat at kfc, for we're all losers, born to fail & to die. Losers, eat at Arby's. Feb 16, 2015 ", 
"There, at the end of the world, beneath the bloody hooves of those horsemen ushering in the eternal doom, arbys will do 2 for 1 curly fries Feb 16, 2015 ", 
"Bae: come over Me: can't. Pondering my irrelevance in an empty universe Bae: my parents are at Arby's Me: please tell them to enjoy Arby's Feb 15, 2015 ", 
"Joke time! How would you order a beef n cheddar at a German Arby's? A: existence is meaningless and life as you know it is inconsequential Feb 15, 2015 ", 
"Why not take her to Arby's tonight? Why not just wear what you've got on? why not give up on the fiction of joy? Arby's: romance incarnate. Feb 14, 2015 ", 
"Your parents have had sex. It doesn't get much darker than that. Have a Valentine's Day and please continue eating at Arby's. Feb 14, 2015 ", 
"No one loves you, for love does not exist. Nothing matters. Enjoy Valentine's Day. Your local Arby's awaits. Feb 14, 2015 ", 
"Friday the 13th eve: test your luck at Arby's. feed the abyss. die anyway. Luck's a pointless abstraction, as is life. Arbys: God hates you. Feb 14, 2015 ", 
"They say today is bad luck. Well, Arby's is open. Those two statements are unrelated. Arby's: the misery of life has no effect on our hours Feb 13, 2015 ", 
"Wanna feel old? You were a non sentient nothing for infinite time before you were born & will soon return to that state. Enjoy Arby's. Feb 12, 2015 ", 
"I'm thinkin life is meaningless. I'm thinkin the universe is a giant random accident. I'm thinkin fuck everything. I'm thinkin Arby's. Feb 12, 2015 ", 
"The birth of your child, your first snowfall, a shooting star: All meaningless in the face of the void. Arby's: may as well order the large. Feb 11, 2015 ", 
"It's hump day! Celebrate this meaningless distinction by consuming a pig, cow or bird. Arby's: there are piles of delicious dead everywhere. Feb 11, 2015 ", 
"When the blood falls from the sky and corpses litter the trails, when the sun burns black and death has become us all, think Arby's. Feb 10, 2015 ", 
"Did I die? Take it from Arbys: there is no comfort in the void. As dead gods toyed with this corpse, I hope you continued enjoying arby's. Feb 10, 2015 ", 
"Let's meet down at the old Arby's where there's no right or wrong, no good or evil. Just sandwiches & men. waiting to kill. waiting to die. Feb 06, 2015 ", 
"Ever feel like no one cares if you live or die? Commiserate w a yummy Arby's chicken bacon Swiss. No one cared if it lived or died either. Feb 06, 2015 ", 
"Your soul is useless. Lock it in the basement. Chain it to the radiator. Beat it. choke it. feed it Arby's. Give it a meal for just $2 more! Feb 05, 2015 ", 
"We've all made mistakes. We've all hurt others. We've all tasted the blood of innocents. Enjoy Arby's: now serving the blood of innocents. Feb 05, 2015 ", 
"McDonalds is trying to buy you with love. Check out THIS counter offer: suffer and let Arby's be your fuel. Die. Arby's: no more nonsense. Feb 04, 2015 ", 
"You are what you eat. You=Arby's. Worms are you. The earth is worms. The sun is the earth. The void is the sun. Nothing's everything. Arby's Feb 04, 2015 ", 
"Bask in the aroma of charred flesh, and gorge on our hush puppies. Drink horsey sauce right from the pump. Arby's: you're already dead. Feb 03, 2015 ", 
"Please have enthusiasm for the green shake thing w the brown veins in it that we're serving for a limited time. Arby's: offering consumables Feb 03, 2015 ", 
"Today, why not choose Arby's for lunch: no clowns, no tacos, no kings, no god, no hope, no bullshitting. You will die. Enjoy Arby's. Feb 03, 2015 ", 
"New England: enjoy the puppet show while it lasts. When the curtain is pulled back, you'll see only the eternity of oblivion. Enjoy Arby's. Feb 02, 2015 ", 
"Seattle: welcome to empty darkness. Welcome to Arby's. Feb 02, 2015 ", 
"Enjoy watching human men crushing and destroying each other as you continue to lazily decay. Arby's: we too know the super bowl is on. Feb 01, 2015 ", 
"People who say 'never surrender' are fools. None of us has any choice but to one day surrender and die. Arby's: surrender to deliciousness. Feb 01, 2015 ", 
"No one loves you. So you may as well eat at Arby's. Arby's: Meat. Curly fries. Seasonal shakes. Other shit. Feb 01, 2015 ", 
"Which of our sandwiches do you wanna chug most? Which frosty drink matches your steez? How do you cope with infinite nothingness, bruh? Jan 31, 2015 ", 
"Even the bravest man crumbles when staring down death and the truth that there's no god. In the meantime, stare down an Arby's Angus philly. Jan 30, 2015 ", 
"You're too good for Arby's? You're nothing. Arby's is nothing. You're Arby's. And your Kings Hawaiian Fish Deluxe is a limited time offer. Jan 29, 2015 ", 
"What is cheese? What is meat? What is a meal? Answers mean nothing. Arby's: consume and enjoy. Jan 29, 2015 ", 
"Drain the blood, cure and slice the flesh, season and fry the potatoes, feed them the sugar water. Be born. Toil. Die. Arby's. We sell food. Jan 28, 2015 ", 
"Ever wake up with no memory of the night before to the nightmarish realization that the blood all over you is not your own? Enjoy Arby's. Jan 28, 2015 ", 
"Your sad existence will pull your soul to pieces, and we do the same thing to animals and put em on buns, because fuck it. Arby's: fuck it. Jan 27, 2015 ", 
"Roses will die. Violets will too. May as well try Arby's cordon bleu. Jan 27, 2015 ", 
"You know what? Yeah, in hindsight burgers were the way to go. Whatever. Fuck it. Fuck you. Arby's. We do other shit that's not burgers. Jan 27, 2015 ", 
"Whoever you are, be. Ar. Bys. Arby's. Whatever. Come up with your own shit then. Jan 25, 2015 ", 
"Everyone is very disappointed in you except for Arby's. Eat at Arby's. Jan 24, 2015 ", 
"Remember that poor pig that crapped on his own balls? He's bacon now. Arby's: no tears, no mercy. Jan 23, 2015 ", 
"Hey peeps! Which of our funky fresh sandwiches best reflects your weekend party style? Jk, we don't care. No one cares. Life is pain. Jan 23, 2015 ", 
"Nuggets were birds. Beef n cheddars were cows. Life was and will always be pain. Arby's: we're not bullshitting. Jan 23, 2015 ", 
"Burgers are a joke. Sliced beef is a joke. Tacos are a joke. Arby's: get High in our bathrooms. Jan 23, 2015 ", 
"Arby's: there's almost never a line here. Jan 22, 2015 ", 
"Hey! It's almost the weekend! What's your favorite Arby's snack to enjoy as you trudge meaninglessly towards doom? Jan 22, 2015 ", 
"Yeah sure, McDonald's and Burger King, they've got dip...dipSHITS. fuck it. Arby's doesn't care. Arby's says whatever the fuck Arby's wants Jan 22, 2015 ", 
"We only have Pepsi, actually. Where's your God now? Jan 22, 2015 ", 
"Hey, you guys know what's really funny? Nothing. Continue eating at Arby's please. Jan 21, 2015 ", 
"Do drugs. Punch a stranger. Make love to your cousin. Enjoy Arby's. Arby's doesn't judge. Arby's doesn't care. Jan 21, 2015 ", 
"Arby's is: A) named for our founder, Chet Arby B) an acronym for America's Roast Beef Yes Sir C) a meaningless monument to a dead god Jan 21, 2015 ", 
"If your life has lost all meaning, why not have breakfast at Arby's? Served all day, so don't bother getting out of bed until whenever Jan 21, 2015 ", 
"There's no god so why not worship our smokehouse brisket? You'll literally get the same results. Jan 20, 2015 ", 
"There's nothing like the delicious taste of Arby's because there is nothing. Happiness, friends, lovers: illusions. Arby's: the void beckons Jan 20, 2015 ", 
"Do you prefer mozz sticks or hashbrowns? Roast beef or ham? Who cares? Arby's. we all die alone. Jan 15, 2015 ", 
"Killed a man? Left your family? Plummeted into a shameful addiction spiral? None of it matters to Arby's. please enjoy Arby's. Jan 15, 2015 ", 
"We aren't mopping the floors tonight because fuck it. All Arby's locations will eventually be destroyed in war or sucked back into the sun. Jan 15, 2015 ", 
"There is no truth but death. And Arby's. enjoy 5 beef n cheddars for five bucks. Why not? Arby's. Jan 15, 2015 ", 
"God is not dead. there was never a god. Horsey Sauce can be consumed on fries. Jan 14, 2015 ", 
"Arby's. Whatever. It's better than nothing. Jan 14, 2015 "];

var InfiniteLoop = require('infinite-loop');
var il = new InfiniteLoop;

function randomPepe() {
	return words[Math.floor(Math.random() * words.length)];
};
il.add(randomPepe, []);

il.run();

console.log(randomPepe());

var Discord = require("discord.js");
var bot = new Discord.Client();
bot.on("message", (message) => {
  if (message.content.startsWith("!arbys")) {
    message.channel.sendMessage(randomPepe());
  }
});

bot.login("Mjk4NDQ1NDE5MzA5MDM5NjE2.C8PcfQ.Ld03QlaIv08ugpMSI0s3LWfD0uE");
